### ISSUE TITLE
Consider updating the pinned version of pedantic in the docs (or unpinning)

### ISSUE THREAD

**Issue by pq** [dart-lang/pedantic#11]
The instructions in https://github.com/dart-lang/pedantic#enabled-lints suggest this dependency snippet:

```
dependencies:
  pedantic: '1.1.0'
```

Should this be updated to `1.4.0`?  What about unpinning and changing it to `^1.0.0`?

/cc @davidmorgan

**Comment by davidmorgan** [comment]
Let's just keep the example updated for now. Thanks!
