### ISSUE TITLE
Add a justForSideEffects method that justifies why a property access is called

### ISSUE THREAD

**Issue by srawlins** [dart-lang/pedantic#13]
(Derived from https://github.com/dart-lang/sdk/issues/35513, a request for `@sideEffects)

Take a class like so:

```dart
class Store {
  Map _m;
  Map get m {
    // Fetch m from somewhere, store in `_m`, and return it.
  }
}
```

There are cases where code (tests in particular), are testing the side effects without using the returned value. So you might see something like:

```dart
new S().m;
```

This looks like an unnecessary_statements violation, because unnecessary_statements assumes that all property access calls, even if they have side effects, are not _just_ called for the side effects. Here are some other lint rules that assume that property access is not called for the side effects:

```dart
class A {
  B get b {
    print('b was gotten');
    return B();
  }
}

class B {
  int c, d;
}

void f() {
  if (a.b.c == null) {
    a.b.c = 7; // triggers a prefer_conditional_assignment lint report.
  }

  a.b
      ..c = 1
      ..d = 2;
  a.b.c = 3; // triggers a cascade_invocations lint report.

  a.b; // triggers unnecessary_statement lint report.

  a.b.c = 7;
  return a.b.c; // triggers a join_return_with_assignment lint report.
}
```

It could be called `externalSideEffects` or `importantSideEffects` or `meaningfulSideEffects` or something as well.

So the above code would be rewritten, to avoid the lint rules:

```dart
class A {
  B get b {
    print('b was gotten');
    return B();
  }
}

class B {
  int c, d;
}

void f() {
  if (externalSideEffects(a.b).c == null) {
    a.b.c = 7; // no more prefer_conditional_assignment
  }

  externalSideEffects(a.b)
      ..c = 1
      ..d = 2;
  a.b.c = 3; // no more cascade_invocations

  externalSideEffects(a.b); // no more unnecessary_statement

  a.b.c = 7;
  return externalSideEffects(a.b).c; // no more join_return_with_assignment
}
```

**Comment by matanlurey** [comment]
@srawlins Let's close for now 1.5 years later - can always re-open.
