### ISSUE TITLE
Style recommendations for library developers

### ISSUE THREAD

**Issue by micimize** [dart-lang/pedantic#17]
> Note on Flutter SDK Style: some lints were created specifically to support Flutter SDK development. Flutter app developers should instead use standard Dart style as described in Effective Dart, and should not use these lints.

This makes it clear that the recommendation for app developers is to defer style decisions to `pedantic`. Is this also the case for general-purpose and flutter-specific libraries?

Related to flutter/flutter#29228

**Comment by davidmorgan** [comment]
The intent of 'app' is to distinguish from flutter _SDK_ developers. So, yes, general purpose and flutter specific libraries should use `package:pedantic`.
