### ISSUE TITLE
Should unnecessary_new be included in the lints?

### ISSUE THREAD

**Issue by thosakwe** [dart-lang/pedantic#18]
Because `new` is optional in Dart 2, does it make sense to discourage its usage? Also I guess that by extension, if `unnecessary_new` were included, then that would imply that `unnecessary_const` should also be included.

Do you think this that this is a worthwhile addition, or unnecessary?

**Comment by davidmorgan** [comment]
Yes, `unnecessary_new` will be added soon.

`package:pedantic` gives the set of lints that are enforced internally at google. We're currently putting more effort into enforcing new lints (which involves cleaning up all the code we have, first), so you can expect to see quite a few new lints soon.

We are currently undecided on `unnecessary_const`; it's more complex than `unnecessary_new`. We'll likely focus on other, more obviously useful, lints first.
