### ISSUE TITLE
Who lints the lints?

### ISSUE THREAD

**Issue by kentcb** [dart-lang/pedantic#23]
Vague title, but I couldn't resist it sorry.

Here's my situation: I want to use pedantic but I've also got quite a few extra lints that I want enabled. Some of those will almost certainly be included in pedantic itself at some point. Since the point of pedantic is to adhere to Google's standard, the lints I add are useful as a point of _difference_. However, nothing guarantees that they are a point of difference.

What's the guidance in this situation? It would be nice to know that if my lint configuration becomes redundant at some point (due to a newer pedantic release) that I would be notified, but it seems that this is not the case (I just tried adding a lint that pedantic has already enabled). Is my only recourse to manually pick through the lints I have enabled and see whether they're redundant? Seems finicky.

**Comment by srawlins** [comment]
Similar discussion over here: https://github.com/dart-lang/linter/pull/1553

**Comment by davidmorgan** [comment]
You could put something in your presubmit if you like :) ... this is far from beautiful, could definitely be improved:

```bash
LINTS=$(\
    cat $(\
        cat .packages | \
        grep pedantic | \
        sed -e 's#.*file://##')/analysis_options*.yaml | \
        egrep '^    -' | \
        sed -e 's# ##g' | \
        sort -u; \
        cat analysis_options.yaml | \
        egrep '^    -' | \
        sed -e 's# ##g');
if [[ $(echo $LINTS | \
    tr ' ' '\n' | \
    sort -u | \
    wc -l) != $(echo $LINTS | \
    tr ' ' '\n' | \
    wc -l) ]]; then \
   echo Redundant lint with pedantic.; exit 1; \
fi
```

**Comment by pq** [comment]
Thanks for kicking off the conversation @kentcb.  As @srawlins mentioned, we've talked a bit about this problem but haven't settled on a solution so your input is appreciated.  Do you have an ideal flow in mind?  Would a presubmit suffice?  Would you like feedback in the IDE?

**Comment by kentcb** [comment]
Ideally, I'd like the problems to be surfaced in the same manner as other lints. For me, that means the **PROBLEMS** panel in VS Code.

Presubmits are a nice idea, but aren't portable. It's not uncommon for team members to use different operating systems and - in my experience at least - this makes the use of hooks untenable.

**Comment by pq** [comment]
Thanks @kentcb.  I've opened a feature request on the linter here: https://github.com/dart-lang/linter/issues/1588.  Alternatively, we could do this in the analyzer but, as @bwilkerson points out, it may not be universally desired so a simple opt-in model may be best.

Feel free to chime in with any additional thoughts there!

**Comment by matanlurey** [comment]
Closed - refer to https://github.com/dart-lang/linter/issues/1588 going forward.
