### ISSUE TITLE
sort_constructors_first shows improper suggestions in Flutter

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [dart-lang/pedantic#26]
```dart
const ValueSlider(
      {Key key,
      @required this.onChanged,
      @required this.labels,
      @required this.values,
      @required this.type,
      this.status = AttendanceStatus.none})
      : super(key: key);
```
this is caught by the linter even though Flutter puts Key first by default.

**Comment by a14n** [comment]
I don't understand what you mean. [sort_constructors_first](https://dart-lang.github.io/linter/lints/sort_constructors_first.html) ensures you _sort constructor declarations before other members_.

**Comment by ThinkDigitalSoftware** [comment]
@a14n Right. It catches correctly, however, I've read in certain linting rules that they have conditions when they're run and when they aren't. It wouldn't be proper for a warning to suggest that you move away from Google suggested practices

**Comment by bwilkerson** [comment]
We don't limit the lints supported by the linter to all be self-consistent. We won't enable inconsistent lints in the pedantic rule set, but don't guarantee that all of the supported lints will be consistent with these rules.

**Comment by ThinkDigitalSoftware** [comment]
OK, So it's probably best to disable the rule then you're saying?

**Comment by bwilkerson** [comment]
What's "best" depends on what your goal is. But if your goal is to follow all of the Flutter recommended rules **and** all the rules in pedantic, then recognize that those lists are controlled by two different groups and they don't always agree about matters of style. I suspect that in some cases you're going to have to decide for yourself which rules you want to follow and which to ignore.

**Comment by ThinkDigitalSoftware** [comment]
Makes sense. Thanks!
