### ISSUE TITLE
How to ignore the rule of lines_longer_than_80_chars when run "flutter format -n --set-exit-if-changed ."

### ISSUE THREAD

**Issue by qiuyu-y** [dart-lang/pedantic#27]
when i run 'flutter format -n --set-exit-if-changed ." , it return 'Formatting failed: 1' , how can i ignore the rule of  lines_longer_than_80_chars to let it reture success

**Comment by davidmorgan** [comment]
`package:pedantic` does not have `lines_longer_than_80_chars`. I think this question needs to go to the flutter team/project :)
