### ISSUE TITLE
Remove/adjust `curly_braces_in_flow_control_structures`

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [dart-lang/pedantic#30]
From https://github.com/modulovalue/extra_pedantic/issues/1:

>This is intended to help prevent the dangling else problem, however, to avoid that problem, curly braces have to be added in very few scenarios and in all the other cases this lint is unhelpful.

I do not understand why this lint will add warnings for statements like the following:

```dart
if (condition)
  someLongStatementThatIsAutomaticallyFormattedOntoANewLine();

for (...) doStuff();
```

Having to add curly braces in these scenarios seems unproductive to me.  
I created a linter issue about this as well: https://github.com/dart-lang/linter/issues/1763

**Comment by davidmorgan** [comment]
The linter is the right place to discuss this.
