### ISSUE TITLE
Rephrase README - the lints reach outside the scope of effective Dart

### ISSUE THREAD

**Issue by natebosch** [dart-lang/pedantic#38]
The readme says:

> Note that everything here fits within the guidelines set out in Effective Dart. You could think of that document as the design and this package as one possible partial implementation.

I don't think that is quite true. Effective Dart is intentionally not opinionated about double vs single quotes, for instance.

I think we should find a way to explain that in addition to best practices, we also add lints for the sake of having consistent style when there are competing but equal options.

**Comment by davidmorgan** [comment]
Thanks, you are correct. I think I'll explicitly list lints that are stricter than Effective Dart.
