### ISSUE TITLE
prefer_single_quotes needs an automatic fix

### ISSUE THREAD

**Issue by Pacane** [dart-lang/pedantic#47]
Since this rule is enabled by default in pedantic, my project has more than 6000 warnings.

Would it be an option to add a dartfmt fix for this, as there's no easy way to change it for us without analyzing each occurrence for an escaped single quote in the strings.

**Comment by awhitford** [comment]
How does one use the "fix"?  I tried running `dartfmt`, but it does not address this issue.  I am using **Dart version 2.8.4** and **Flutter version 1.17.3**.

**Comment by Pacane** [comment]
Use the package dartfix, it contains the fix for that in the latest version

**Comment by bwilkerson** [comment]
The fixes are also available in many editors, such as IntelliJ and VS Code.

**Comment by Pacane** [comment]
Last time I checked it wasn't available in IDEs (the one to bulk fix quotes
in multiple files), I could only find the fix within dartfix
