### ISSUE TITLE
Getting dart analyses warning for auto generated file

### ISSUE THREAD

**Issue by polina-c** [dart-lang/pedantic#48]
I am getting noisy warning `Unused import: 'dart:ui'.` for the file 'generated_plugin_registrant.dart'

dart:ui is really unused here, however I do not want to update an auto-generated file

**Comment by srawlins** [comment]
Typically code generators use `// ignore_for_file: unused_import` etc for generated files in which it is hard to generate perfect code. See more on suppression [here](https://dart.dev/guides/language/analysis-options#suppressing-rules-for-a-file).

**Comment by polina-c** [comment]
Yes. This generator does not do this.
I guess the file  'generated_plugin_registrant.dart' is generated by flutter engine. 

Submitted issue to them: https://github.com/flutter/flutter/issues/49983

Should this one be closed?

**Comment by davidmorgan** [comment]
Yes, I'll close it. Thanks :)
