### ISSUE TITLE
Add `lib/unused_lints.yaml`

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pedantic#5]
This could be a list with comments – or a Map with key (lint) + value (description of why not)

It'd be nice to have this in a machine-readable format so it can be used in tools

**Comment by davidmorgan** [comment]
I'm curious, why do you want to use it in tools?

The reason it's in `README.md` right now is it's more human readable :) ... should we have both?

Thanks.

**Comment by natebosch** [comment]
I'm also curious what tool would like this info.

**Comment by kevmoo** [comment]
Use it for tools – so we can validate we're not enforcing lints against our
standard?

**Comment by matanlurey** [comment]
I think we can safely say this isn't something happening.
