### ISSUE TITLE
'flutter pub get' fails for pedantic 1.9.1

### ISSUE THREAD

**Issue by swch01** [dart-lang/pedantic#60]
```
➜ flutter pub get
Because pedantic >=1.9.1 depends on meta ^1.2.0 which doesn't match any versions, pedantic >=1.9.1 is forbidden.
So, because [xxx] depends on pedantic ^1.9.1, version solving failed.
Running "flutter pub get" in [xxx]...
pub get failed (1; So, because [xxx] depends on pedantic ^1.9.1, version solving failed.)
```

The most recent stable version of meta is 1.1.8.

**Comment by davidmorgan** [comment]
Correct; you can't use `1.9.1` yet.

Is this causing problems? If not, the solution is simply to wait :)

Thanks.

**Comment by alextekartik** [comment]
I even think meta 1.2.0 was published too soon...it breaks test_core and by this, all the tests! (https://github.com/dart-lang/test/issues/1292)

**Comment by swch01** [comment]
The `pub.dev` page for pedantic lists `1.9.1` as the current version. If `1.9.1` is unusable, perhaps you could list the current version as `1.9.0`?

**Comment by matanlurey** [comment]
It looks like `meta` has since been updated: https://pub.dev/packages/meta/versions.
